import { Fragment, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";      // ← added useParams
import { useForm, useFieldArray } from "react-hook-form";
import { Dialog, Transition } from "@headlessui/react";
import { toast } from "react-toastify";
import { FiUpload } from "react-icons/fi";
import api from "../../api";

/*── constants ─*/
const AVAIL = [
  { id: "inStock", label: "In-stock" },
  { id: "restocking", label: "Restocking soon" },
  { id: "inactive", label: "Mark as inactive" },
];

const META = [
  { title: "General", body: "Add information about the product here." },
  {
    title: "Product Variants",
    body: "For products with variables, such as size, colour or specs to manage their inventory levels.",
  },
  {
    title: "Product availability",
    body: "Edit inventory levels to better help you manage inventory",
  },
  {
    title: "Product Descriptions & Features",
    body: "Add attributes for this product to create and manage their inventory.",
  },
];

export default function EditProduct() {
  const { id } = useParams();               // ← grab the product ID
  const nav     = useNavigate();

  const {
    register,
    handleSubmit,
    watch,
    control,
    setValue,
    getValues,
    reset,                                  // ← include reset
    formState: { errors, isSubmitting },
  } = useForm({
    mode: "onTouched",
    defaultValues: {
      productName: "",
      productCategory: "",
      brand: "",
      baseRam: "",
      baseStorage: "",
      baseCPU: "",
      costPrice: "",
      sellingPrice: "",
      quantity: 1,
      availability: "inStock",
      status: "Status",
      reorderLevel: 10,
      stockLocation: "",
      productIdMode: "Autogenerated",
      productId: "",
      supplier: "",
      description: "",
      serialNumbers: ["", "", "", "", ""],
      variants: [{ attribute: "", value: "", inputCost: "" }],
      features: [{ key: "", value: "" }],
      existingImages: [],   // NEW
      newImages:      [],   // NEW
      removedImages:  [],   // NEW
    },
  });

  /*── fetch existing product ──*/
  useEffect(() => {
    api.get(`/api/products/${id}`)
      .then(({ data }) => {
        reset({
          productName:     data.productName,
          productCategory: data.productCategory,
          brand:           data.brand,
          baseRam:         data.baseRam,
          baseStorage:     data.baseStorage,
          baseCPU:         data.baseCPU,
          costPrice:       data.costPrice,
          sellingPrice:    data.sellingPrice,
          quantity:        data.quantity,
          availability:    data.availability,
          status:          data.status,
          reorderLevel:    data.reorderLevel,
          stockLocation:   data.stockLocation,
          productIdMode:   data.productId ? "Manual" : "Autogenerated",
          productId:       data.productId || "",
          supplier:        data.supplier,
          description:     data.description,
          serialNumbers:   data.serialNumbers || ["", "", "", "", ""],
          variants:        data.variants       || [{ attribute: "", value: "", inputCost: "" }],
          features:        data.features       || [{ key: "", value: "" }],
          existingImages:  data.images         || [],
          newImages:       [],
          removedImages:   [],
        });
      })
      .catch(err => {
        console.error(err);
        toast.error("Could not load product");
        nav("/inventory");
      });
  }, [id, reset, nav]);

  /* field arrays */
  const { fields: variantF, append: addVariant } = useFieldArray({
    control,
    name: "variants",
  });
  const { fields: featureF, append: addFeature } = useFieldArray({
    control,
    name: "features",
  });
  const { fields: serialF } = useFieldArray({ control, name: "serialNumbers" });

  /* helpers */
  const addImages = (files) =>
    setValue("images", [...getValues("images"), ...files]);

  /*── IMAGE HELPERS ──*/
  const onPick = (files) => {
    setValue("newImages", [...watch("newImages"), ...files]);
  };
  const removeExisting = (url) => {
    setValue("existingImages", watch("existingImages").filter(u => u !== url));
    setValue("removedImages", [...watch("removedImages"), url]);
  };
  const removeNew = (idx) => {
    const arr = [...watch("newImages")];
    arr.splice(idx, 1);
    setValue("newImages", arr);
  };

  /* disable manual ID unless chosen */
  const pidMode = watch("productIdMode");
  useEffect(() => {
    if (pidMode === "Autogenerated") setValue("productId", "");
  }, [pidMode, setValue]);

  /*── handle update ──*/
  const onSubmit = async (data) => {
    const fd = new FormData();

    [
      "productName",
      "productCategory",
      "brand",
      "baseRam",
      "baseStorage",
      "baseCPU",
      "availability",
      "status",
      "stockLocation",
      "productId",
      "description",
      "supplier",
    ].forEach((k) => fd.append(k, data[k] || ""));

    fd.append("sellingPrice",  Number(data.sellingPrice  || 0));
    fd.append("costPrice",     Number(data.costPrice     || 0));
    fd.append("quantity",      Number(data.quantity      || 0));
    fd.append("reorderLevel",  Number(data.reorderLevel  || 0));

    fd.append("serialNumbers", JSON.stringify(data.serialNumbers));
    fd.append("features",      JSON.stringify(data.features));
    fd.append(
      "variants",
      JSON.stringify(
        data.variants.map((v) => ({
          ...v,
          inputCost: Number(v.inputCost || 0),
        }))
      )
    );

    fd.append("removedImages", JSON.stringify(data.removedImages));

    data.newImages.forEach((file) => fd.append("images", file));

    try {
      // ← switch to PUT for update
      await api.put(`/api/products/${id}`, fd, {
        headers: { "Content-Type": "multipart/form-data" },
      });
      toast.success("Product updated");
      nav("/inventory");
    } catch (err) {
      toast.error(err.response?.data?.message || "Could not update product");
      console.error(err);
    }
  };

  /* reusable block (unchanged) */
  const Block = ({ title, body, children, first }) => (
    <section
      className={`${first ? "" : "pt-16"} grid gap-8 md:grid-cols-[260px_1fr]`}
    >
      {/* meta column */}
      <div>
        <h3 className="text-[17px] font-semibold">{title}</h3>
        <p className="mt-1 text-sm leading-5 text-gray-600">{body}</p>
        {first && (
          <div className="mt-6 flex gap-4">
            <button
              type="button"
              onClick={() => nav(-1)}
              className="rounded border border-orange-500 px-6 py-1.5 text-orange-500"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="rounded bg-orange-500 px-6 py-1.5 text-white disabled:opacity-60"
            >
              {isSubmitting ? "Updating…" : "Update"}
            </button>
          </div>
        )}
      </div>

      {/* fields */}
      <div className="space-y-8">{children}</div>
    </section>
  );

  return (
    <form
      onSubmit={handleSubmit(onSubmit)}
      className="mx-auto max-w-[1150px] px-4 sm:px-6 pb-32"
    >
      {/*──────── GENERAL ────────*/}
      <Block {...META[0]} first>
        <input
          {...register("productName", { required: "Product name is required" })}
          placeholder="Enter product name"
          className="input"
        />

        <div className="grid gap-6 sm:grid-cols-2">
          <select
            {...register("brand", { required: "Brand required" })}
            className="input"
          >
            <option value="" disabled hidden>
              Enter brand name
            </option>
            <option>Dell</option>
            <option>HP</option>
          </select>
          <select
            {...register("productCategory", { required: "Category required" })}
            className="input"
          >
            <option value="" disabled hidden>
              Enter product category
            </option>
            <option>Laptops</option>
            <option>Monitor</option>
            <option>Accessories</option>
          </select>
        </div>

        {/* specs */}
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {["baseRam", "baseStorage", "baseCPU"].map((k) => (
            <select key={k} {...register(k)} className="input">
              <option value="" disabled hidden>
                {k === "baseRam"
                  ? "Base Ram"
                  : k === "baseStorage"
                  ? "Base Storage"
                  : "Base CPU/Processor"}
              </option>
              <option>8GB</option>
              <option>16GB</option>
              <option>32GB</option>
            </select>
          ))}
        </div>

        {/* prices */}
        <div className="grid gap-6 sm:grid-cols-2">
          <input
            {...register("costPrice", { valueAsNumber: true })}
            placeholder="Enter Cost Price per Unit (NGN)"
            className="input"
          />
          <input
            {...register("sellingPrice", {
              required: "Selling price required",
              valueAsNumber: true,
            })}
            placeholder="Enter Selling Price per Unit (NGN)"
            className="input"
          />
        </div>

        <input
          type="number"
          {...register("quantity", { valueAsNumber: true })}
          placeholder="Enter Product quantity"
          className="input"
        />

        {/* Serial Number(s) – 5 lines, 1 col on mobile → 2 cols ≥ 640 px */}
        <div className="rounded border bg-white p-4">
          <p className="mb-3 font-medium">Serial Number(s)</p>

          <div className="grid gap-y-3 gap-x-8 sm:grid-cols-2">
            {[0, 1, 2, 3, 4].map((idx) => (
              <div key={idx} className="flex items-center gap-2">
                {/* index label */}
                <span className="w-3 text-[10px] text-gray-400 sm:w-4 sm:text-xs">
                  {idx + 1}
                </span>

                {/* input */}
                <input
                  {...register(`serialNumbers.${idx}`)}
                  placeholder="Enter Serial number"
                  className="input flex-1"
                />
              </div>
            ))}
          </div>
        </div>

        <input
          {...register("supplier")}
          placeholder="Enter supplier name"
          className="input"
        />
      </Block>

      {/*──────── VARIANTS ────────*/}
      <Block {...META[1]}>
        <div className="flex items-center justify-between">
          <h4 className="font-medium">Product Variants</h4>
          <button
            type="button"
            onClick={() =>
              addVariant({ attribute: "", value: "", inputCost: "" })
            }
            className="text-sm font-medium text-orange-500"
          >
            Add Variants
          </button>
        </div>

        {variantF.map((v, idx) => (
          <div
            key={v.id}
            className="grid gap-4 mb-4 sm:grid-cols-2 lg:grid-cols-3"
          >
            <input
              {...register(`variants.${idx}.attribute`)}
              placeholder="Attribute (e.g. ram)"
              className="input"
            />
            <input
              {...register(`variants.${idx}.value`)}
              placeholder="Value (e.g. 8GB)"
              className="input"
            />
            <input
              {...register(`variants.${idx}.inputCost`, {
                valueAsNumber: true,
              })}
              placeholder="Input cost"
              className="input"
            />
          </div>
        ))}
      </Block>

      {/*──────── AVAILABILITY ────────*/}
      <Block {...META[2]}>
        <div>
          <label className="form-label">Stock Status</label>
          <div className="flex flex-wrap gap-8">
            {AVAIL.map((o) => (
              <label key={o.id} className="flex items-center gap-2 text-sm">
                <input
                  type="radio"
                  value={o.id}
                  {...register("availability")}
                  className="accent-orange-500"
                />
                {o.label}
              </label>
            ))}
          </div>
        </div>

        <div className="grid gap-1">
          <div className="grid gap-6 sm:grid-cols-[1fr_120px]">
            <select {...register("status")} className="input">
              <option>Status</option>
              <option>Incoming</option>
              <option>Archived</option>
            </select>
            <input
              type="number"
              {...register("reorderLevel", { valueAsNumber: true })}
              className="input"
            />
          </div>
          <p className="hidden sm:block text-xs text-gray-400">
            (Low stock alert when stock is less than)
          </p>
        </div>

        <select {...register("stockLocation")} className="input">
          <option value="" disabled hidden>
            Enter product category
          </option>
          <option>Component 180</option>
          <option>Warehouse A</option>
        </select>

        {/* Product ID */}
        <div className="grid sm:grid-cols-[160px_1fr] md:grid-cols-[180px_1fr] gap-0.5">
          <select
            {...register("productIdMode")}
            className="input rounded-r-none"
          >
            <option>Autogenerated</option>
            <option>Manual</option>
          </select>
          <input
            {...register("productId", { required: pidMode === "Manual" })}
            disabled={pidMode === "Autogenerated"}
            placeholder={
              pidMode === "Autogenerated"
                ? "Generated automatically"
                : "Enter product ID"
            }
            className="input rounded-l-none"
          />
        </div>
      </Block>

      {/*──────── DESC & FEATURES ────────*/}
      <Block {...META[3]}>
        {/* ← REPLACED IMAGE SECTION: */}
        <div className="space-y-2">
          <label className="block font-medium">Upload Product Image</label>
          <div className="flex flex-wrap gap-3">
            {watch("existingImages").map(url => (
              <div key={url} className="relative">
                <img src={url} alt="" className="h-24 w-24 object-cover rounded"/>
                <button
                  type="button"
                  onClick={()=>removeExisting(url)}
                  className="absolute top-0 right-0 bg-white rounded-full p-1 text-red-600 hover:bg-red-100"
                >×</button>
              </div>
            ))}

            {watch("newImages").map((f,i) => {
              const src = URL.createObjectURL(f);
              return (
                <div key={i} className="relative">
                  <img src={src} alt="" className="h-24 w-24 object-cover rounded"/>
                  <button
                    type="button"
                    onClick={()=>removeNew(i)}
                    className="absolute top-0 right-0 bg-white rounded-full p-1 text-red-600 hover:bg-red-100"
                  >×</button>
                </div>
              );
            })}

            <label className="flex h-24 w-24 cursor-pointer items-center justify-center rounded border border-dashed">
              <FiUpload className="h-6 w-6 text-gray-500"/>
              <input
                type="file"
                multiple
                className="hidden"
                onChange={e => onPick(Array.from(e.target.files))}
              />
            </label>
          </div>
        </div>

        {/* your existing description & features markup */}
        <textarea
          rows={3}
          {...register("description")}
          placeholder="Enter a description..."
          className="input resize-none"
        />

        <div className="mb-1 flex items-center justify-between">
          <h4 className="font-medium">Features</h4>
          <button
            type="button"
            onClick={() => addFeature({ key: "", value: "" })}
            className="text-sm font-medium text-orange-500"
          >
            + Add specifications
          </button>
        </div>

        {featureF.map((f, i) => (
          <div key={f.id} className="mb-3 grid gap-4 sm:grid-cols-2">
            <input
              {...register(`features.${i}.key`)}
              placeholder="Attribute (e.g. RAM)"
              className="input"
            />
            <input
              {...register(`features.${i}.value`)}
              placeholder="Value (e.g. 8GB)"
              className="input"
            />
          </div>
        ))}
      </Block>


      {/* validation summary */}
      {Object.keys(errors).length > 0 && (
        <div className="mt-10 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">
          {Object.values(errors).map((e, i) => (
            <p key={i}>• {e.message}</p>
          ))}
        </div>
      )}
    </form>
  );
}
