import React, { useState } from 'react'
import { FiChevronDown } from 'react-icons/fi'

export default function SettingPreference() {
  /* ─────────────────────────────────────
     Local toggles – replace with real state / API calls later
  ───────────────────────────────────── */
  const [autoTZ, setAutoTZ]           = useState(false)
  const [lowStock, setLowStock]       = useState(true)
  const [includeTax, setIncludeTax]   = useState(true)
  const [emailNotif, setEmailNotif]   = useState(false)

  /* quick helper for the nice orange toggle */
  const Toggle = ({ enabled, setEnabled }) => (
    <label className="relative inline-flex cursor-pointer items-center">
      <input
        type="checkbox"
        className="sr-only peer"
        checked={enabled}
        onChange={() => setEnabled(!enabled)}
      />
      <div
        className="h-5 w-10 rounded-full bg-gray-200 
                   peer-focus:ring-2 peer-focus:ring-orange-500
                   peer-checked:bg-orange-500 peer-transition-colors"
      />
      <div
        className="absolute left-0.5 top-0.5 h-4 w-4 rounded-full bg-white 
                   shadow transition-transform peer-checked:translate-x-5"
      />
    </label>
  )

  return (
    <section className="space-y-10">
      {/* ───────────────  Header  ─────────────── */}
      <header className="space-y-1">
        <h2 className="text-lg font-semibold text-gray-800">Preference</h2>
        <p className="text-sm text-gray-500">
          Edit general information about your business
        </p>
      </header>

      {/* ───────────────  Time zone  ─────────────── */}
      <div className="space-y-2">
        <label className="block text-sm font-medium text-gray-700">
          Time Zone
        </label>

        <div className="flex flex-col sm:flex-row sm:items-center gap-4">
          {/* select */}
          <div className="relative flex-1">
            <select
              className="w-full rounded-md border-gray-300 pr-10
                         focus:border-orange-500 focus:ring-orange-500"
              defaultValue="Africa/Lagos"
            >
              <option value="Africa/Lagos">(GMT +01:00) Africa/Lagos</option>
              <option value="America/New_York">(GMT -05:00) America/New York</option>
              <option value="Asia/Tokyo">(GMT +09:00) Asia/Tokyo</option>
            </select>
            <FiChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-gray-400" />
          </div>

          {/* auto toggle */}
          <div className="flex items-center gap-3">
            <Toggle enabled={autoTZ} setEnabled={setAutoTZ} />
            <span className="text-sm text-gray-700">Set Automatically</span>
          </div>
        </div>
      </div>

      {/* ───────────────  Inventory  ─────────────── */}
      <header className="pt-2">
        <h3 className="text-sm font-semibold text-gray-800">
          Inventory Settings
        </h3>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Product ID rule */}
        <div className="space-y-1">
          <label className="block text-sm font-medium text-gray-700">
            Product ID
          </label>
          <p className="text-xs text-gray-500">
            Control how Product ID’s are generated
          </p>
          <div className="relative">
            <select
              className="mt-1 w-full rounded-md border-gray-300 pr-10
                         focus:border-orange-500 focus:ring-orange-500"
              defaultValue="auto"
            >
              <option value="auto">Autogenerated</option>
              <option value="manual">Manual</option>
            </select>
            <FiChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-gray-400" />
          </div>
        </div>

        {/* Current ID count */}
        <div className="space-y-1">
          <label className="block text-sm font-medium text-gray-700">
            Current ID Count
          </label>
          <input
            type="number"
            className="mt-1 w-full rounded-md border-gray-300
                       focus:border-orange-500 focus:ring-orange-500"
            value={1002}
            readOnly
          />
        </div>
      </div>

      {/* Low-stock toggle */}
      <div className="flex items-center justify-between pt-4">
        <div>
          <h4 className="text-sm font-medium text-gray-800">Low Stock Alert</h4>
          <p className="text-xs text-gray-500">
            Alert when stock gets to a certain level
          </p>
        </div>
        <Toggle enabled={lowStock} setEnabled={setLowStock} />
      </div>

      {/* ───────────────  Sales settings  ─────────────── */}
      <header>
        <h3 className="text-sm font-semibold text-gray-800">
          Sales Settings
        </h3>
      </header>

      <div className="flex items-center justify-between">
        <span className="text-sm text-gray-700">
          Taxes (include taxes in invoice)
        </span>
        <Toggle enabled={includeTax} setEnabled={setIncludeTax} />
      </div>

      {/* ───────────────  Email notification  ─────────────── */}
      <header>
        <h3 className="text-sm font-semibold text-gray-800">
          Email Notification
        </h3>
      </header>

      <div className="flex items-center justify-between">
        <p className="text-sm text-gray-700 max-w-md">
          Learn about new products or features and receive updates on how your
          business is performing. Automatically sent to your account email.
        </p>
        <Toggle enabled={emailNotif} setEnabled={setEmailNotif} />
      </div>
    </section>
  )
}
